### ISSUE TITLE
Error: Can't resolve 'babel/polyfill'

### ISSUE THREAD

**Issue by Toso82** [mdibaiee/Equation#11]
I try to use this library in my Angular 4 project.  I import library in typescript

import { Equation } from "equations"; 

It is right?

with ng build give me this error:

ERROR in ./~/equations/dist/index.js
Module not found: Error: Can't resolve 'babel/polyfill' in 'C:\Users\Giacomo\Documents\Visual Studio 2017\Projects\test\my-app\node_modules\equations\dist'
 @ ./~/equations/dist/index.js 13:0-25
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by mdibaiee** [comment]
@Toso82 Hi,

could you please try with the latest version? `equations@1.3.6`

**Comment by Toso82** [comment]
@mdibaiee  Hi,
With update compile well thanks.
