### ISSUE TITLE
PhantomJS Browser error

### ISSUE THREAD

**Issue by xuender** [mdibaiee/Equation#8]
TypeError: 'undefined' is not a function (evaluating 'stack.entries()')

**Comment by mdibaiee** [comment]
Hi, sorry about the issue, may you update equation to see if it works now? The PR you sent is not necessary now. I had forgot to require `babel/polyfill`.

`npm update equation`

**Comment by mdibaiee** [comment]
@xuender Was your problem solved? If so please close the issue.
